language: node_js
node_js:
  - "12"
dist: trusty
sudo: required

branches:
  only:
  - master

before_script:
  - npm install -g @angular/cli

script:
  - ng build --aot --prod --base-href $BASE_REF

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/delivery-do-bem
  on:
    branch: master